version: '3.8'

services:
  booking-scraper:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///booking_hotels.db
      - PORT=8000
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Database is now included in the image
      # - ./booking_hotels.db:/app/booking_hotels.db  # Commented out since DB is in image
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - booking-network
    shm_size: '2gb'  # Increase shared memory for Chrome

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - booking-scraper
    restart: unless-stopped
    networks:
      - booking-network
    profiles:
      - production

networks:
  booking-network:
    driver: bridge

volumes:
  booking_data:
    driver: local
  booking_logs:
    driver: local 